### ISSUE TITLE
read.csv or read_tsv, pick one

### ISSUE THREAD

**Issue by raysinensis** [rnabioco/clustifyr-web-app#15]
the readr versions are much faster, but potentially dangerous
I'd say unify to readr::read_ for now, and then we often a checkbox for "keep rownames" or something like that

**Comment by SidhantPuntambekar** [comment]
So I think if we switch to the readr version of read_csv, the header and separator arguments in the current code become unusable. Not sure if read_csv has functionality for these parameters...

**Comment by raysinensis** [comment]
hmmm,, consider data.table::fread, which infers delim and header pretty well, and can be passed other parameters if needed. Also, somewhat faster than readr too?
@kriemo
